/**
 * 
 */
$(function(){
	$(".best-comment").click(function(){
		$(this).parent().next().slideToggle();
	})
	$(".ans-comment").click(function(){
		$(this).parent().next().slideToggle();
	})
	$(".com-comment").click(function(){
		$(this).parent().parent().next().slideToggle();
	})
})